#!/bin/bash

for dir in /etc/portage/{package.accept_keywords,package.env,package.license,package.mask,package.unmask,package.use,sets}; do
        if [[ -d ${dir} ]]; then
                pushd "${dir}"; # &> /dev/null;
                for file in $(ls .); do
                        [ -f "./${file}" ] && cat "./${file}" | sort -u | sort > "./${file}.sorted_file" && mv "./${file}.sorted_file" "./${file}" -v;
                done
                popd; # &> /dev/null;
        fi
done

